In [1]:
%useLatestDescriptors
%use kandy
%use dataframe

In [2]:
var df_stat_raw = DataFrame.readJson("http://192.168.35.107:7788/nifs/stat")
df_stat_raw.describe()

name,type,count,unique,nulls,top,freq,min,p25,median,p75,max
gru_nam,String,936,3,0,남해,528,남해,남해,남해,서해,서해
sta_cde,String,936,39,0,fgg4c,24,bgj8a,eng5c,ftdk5,fwyo5,wn087
sta_nam_kor,String,936,39,0,거제 가배,24,강릉,남해 미조,영덕,태안 고남,해남 임하
obs_datetime,String,936,24,0,26-07-22 17,39,26-07-22 17,26-07-22 22,26-07-23 04,26-07-23 10,26-07-23 16
tmp_min,String,936,115,0,25.8,32,15.5,21.8,22.9,25.2,28.5
tmp_max,String,936,111,0,25.8,29,16.3,22.0,23.1,25.4,28.5
tmp_avg,String,936,202,0,25.80,22,16.15,21.90,23.00,25.30,28.50

In [3]:
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

val formatter = DateTimeFormatter.ofPattern("yy-MM-dd HH")

var df_stat = df_stat_raw.parse()
    .convert { obs_datetime }.with{ LocalDateTime.parse(it.trim(), formatter)}

df_stat.describe()

kotlin-logging: initializing... active logger factory: Slf4jLoggerFactory

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
gru_nam,String,936,3,0,남해,528,null,null,남해,남해,남해,서해,서해
sta_cde,String,936,39,0,fgg4c,24,null,null,bgj8a,eng5c,ftdk5,fwyo5,wn087
sta_nam_kor,String,936,39,0,거제 가배,24,null,null,강릉,남해 미조,영덕,태안 고남,해남 임하
obs_datetime,java.time.LocalDateTime,936,24,0,2026-07-22T17:00,39,null,null,2026-07-22T17:00,2026-07-22T22:00,2026-07-23T04:00,2026-07-23T10:00,2026-07-23T16:00
tmp_min,Double,936,115,0,25.800000,32,23.172543,2.511502,15.500000,21.800000,22.900000,25.258333,28.500000
tmp_max,Double,936,111,0,25.800000,29,23.348504,2.470190,16.300000,22.000000,23.100000,25.458333,28.500000
tmp_avg,Double,936,202,0,25.800000,22,23.260524,2.488213,16.150000,21.900000,23.000000,25.300000,28.500000

In [4]:
df_stat.plot{

    layout {
        title = "일별 해수 온도 변화"
        size = 2000 to 800

    }

    x("obs_datetime"){
        axis.name = "관측일시"
    }

    y {
        axis {
         //   limits = tmp_min.min().toInt().minus(1)..tmp_max.max().toInt().plus(1)
            name = "Temperature °C"
        }
    }

    line {
        y(tmp_avg)
        color("sta_nam_kor"){
            legend.name = "관측소명"
        }
        type = LineType.DOTTED
        width = 0.6
    }

    ribbon {
        yMin("tmp_min")
        yMax("tmp_max")
        fillColor("sta_nam_kor") {
            legend.name = "관측소명"
        }
        alpha = 0.6
        borderLine.width = 0.0
    }
}

In [5]:
val df_day_raw = DataFrame.readJson("http://192.168.35.107:7788/nifs/seawaterinfo/oneday").parse()

df_day_raw.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,2959,39,0,fth59,141,null,null,bgj8a,byy87,fsch6,fwgf1,wn087
sta_nam_kor,String,2959,39,0,통영 학림,141,null,null,강릉,남해 미조,영덕,태안 고남,해남 임하
obs_datetime,LocalDateTime,2959,47,0,2026-07-22T17:00,63,null,null,2026-07-22T17:00,2026-07-22T22:30,2026-07-23T04:30,2026-07-23T10:30,2026-07-23T16:00
obs_lay,Int,2959,3,0,1,1832,1.492058,0.687364,1,1.000000,1.000000,2.000000,3
wtr_tmp,Double,2959,195,0,26.100000,75,21.062352,4.705477,8.800000,19.300000,22.200000,24.300000,28.500000
gru_nam,String,2959,3,0,남해,1457,null,null,남해,남해,동해,동해,서해
lon,Float,2959,39,0,128.415100,141,127.748357,1.177331,124.729500,126.626900,128.049698,128.699799,129.549698
lat,Float,2959,39,0,34.749802,141,35.692836,1.397728,33.310398,34.606899,34.834801,36.712299,38.368099

In [6]:
df_day_raw.plot {

    layout {
        title = "일별 해수 온도 통계"
        size = 2000 to 800
        x.axis.name = "Observatory"
        y.axis.name = "Temperature"
    }

    boxplot(sta_nam_kor, wtr_tmp) {
        boxes {
            fillColor(Stat.middle) {
                legend{
                    name = "Temperature "
                    breaks(format = "{d}°C")
                }
                scale = continuous(Color.BLUE..Color.RED)
            }
            // Border line color depends on `x` category
            borderLine.color(Stat.x)
            // `identity` position, i.e boxes are overlapping
        }

        outliers {
            // points context + StatBoxplotOutliers context
            // color depends on `x` category
            color(Stat.x){
                legend.name = "Observatory"
            }
        }
    }
}

In [7]:
var df_current_raw = DataFrame.readJson("http://192.168.35.107:7788/nifs/seawaterinfo/current").parse()

df_current_raw.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,63,39,0,bgna3,3,null,null,bgj8a,byy87,fsch6,fwdf1,wn087
sta_nam_kor,String,63,39,0,강릉,3,null,null,강릉,남해 미조,영덕,완도 청산,해남 임하
obs_datetime,LocalDateTime,63,1,0,2026-07-23T16:00,63,null,null,2026-07-23T16:00,2026-07-23T16:00,2026-07-23T16:00,2026-07-23T16:00,2026-07-23T16:00
obs_lay,Int,63,3,0,1,39,1.492063,0.692658,1,1.000000,1.000000,2.000000,3
wtr_tmp,Double,63,50,0,22.600000,4,21.438095,4.834300,9.500000,19.733333,22.300000,25.133333,28.500000
gru_nam,String,63,3,0,남해,31,null,null,남해,남해,동해,동해,서해
lon,Float,63,39,0,128.949203,3,127.747460,1.186696,124.729500,126.626900,128.049698,128.699799,129.549698
lat,Float,63,39,0,37.799000,3,35.693368,1.408392,33.310398,34.620249,34.834801,36.696299,38.368099

In [8]:
val df_current =  df_current_raw.insert("관측층"){
    when(this.obs_lay){
        1 -> "표층"
        2 -> "중층"
        3 -> "심층"
        else -> ""
    }
}.after("obs_lay")

df_current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,63,39,0,bgna3,3,null,null,bgj8a,byy87,fsch6,fwdf1,wn087
sta_nam_kor,String,63,39,0,강릉,3,null,null,강릉,남해 미조,영덕,완도 청산,해남 임하
obs_datetime,LocalDateTime,63,1,0,2026-07-23T16:00,63,null,null,2026-07-23T16:00,2026-07-23T16:00,2026-07-23T16:00,2026-07-23T16:00,2026-07-23T16:00
obs_lay,Int,63,3,0,1,39,1.492063,0.692658,1,1.000000,1.000000,2.000000,3
관측층,String,63,3,0,표층,39,null,null,심층,중층,표층,표층,표층
wtr_tmp,Double,63,50,0,22.600000,4,21.438095,4.834300,9.500000,19.733333,22.300000,25.133333,28.500000
gru_nam,String,63,3,0,남해,31,null,null,남해,남해,동해,동해,서해
lon,Float,63,39,0,128.949203,3,127.747460,1.186696,124.729500,126.626900,128.049698,128.699799,129.549698
lat,Float,63,39,0,37.799000,3,35.693368,1.408392,33.310398,34.620249,34.834801,36.696299,38.368099

In [9]:
df_current
    .select{sta_nam_kor and wtr_tmp and "관측층"}
    .plot {
        layout {
            title = "관측 층별 해수 온도"
            size = 2600 to 600
            xAxisLabel = "Observatory"
            yAxisLabel = "Temperature( °C )"
        }

        bars {
            x(sta_nam_kor)

            y(wtr_tmp)

            fillColor("관측층") {
                legend{
                    name = "Ocean Layer"
                }
                scale =  categoricalColorHue()
            }
        }
    }