In [7]:
//%useLatestDescriptors
%use kandy
%use dataframe

In [2]:
var df_stat_raw = DataFrame.readJson("http://192.168.35.107:7788/nifs/stat")
df_stat_raw.describe()

name,type,count,unique,nulls,top,freq,min,p25,median,p75,max
gru_nam,String,936,3,0,남해,528,남해,남해,남해,서해,서해
sta_cde,String,936,39,0,fgg4c,24,bgj8a,eng5c,ftdk5,fwyo5,wn087
sta_nam_kor,String,936,39,0,거제 가배,24,강릉,남해 미조,영덕,태안 고남,해남 임하
obs_datetime,String,936,24,0,26-06-07 13,39,26-06-07 13,26-06-07 18,26-06-08 00,26-06-08 06,26-06-08 12
tmp_min,String,936,87,0,18.9,50,0.2,18.3,18.9,19.7,22.9
tmp_max,String,936,89,0,19.1,52,0.2,18.4,19.0,19.8,23.0
tmp_avg,String,936,150,0,18.60,35,0.20,18.30,18.95,19.75,22.95

In [3]:
var df_stat = df_stat_raw.convert { tmp_min and  tmp_max and  tmp_avg }.with { it.toFloat() }
df_stat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
gru_nam,String,936,3,0,남해,528,null,null,남해,남해,남해,서해,서해
sta_cde,String,936,39,0,fgg4c,24,null,null,bgj8a,eng5c,ftdk5,fwyo5,wn087
sta_nam_kor,String,936,39,0,거제 가배,24,null,null,강릉,남해 미조,영덕,태안 고남,해남 임하
obs_datetime,String,936,24,0,26-06-07 13,39,null,null,26-06-07 13,26-06-07 18,26-06-08 00,26-06-08 06,26-06-08 12
tmp_min,Float,936,87,0,18.900000,50,18.366132,3.366554,0.200000,18.299999,18.900000,19.700001,22.900000
tmp_max,Float,936,89,0,19.100000,52,18.467521,3.375456,0.200000,18.400000,19.000000,19.799999,23.000000
tmp_avg,Float,936,150,0,18.600000,35,18.416827,3.370268,0.200000,18.299999,18.950001,19.750000,22.950001

In [5]:
import org.jetbrains.letsPlot.core.spec.plotson.theme
import org.jetbrains.letsPlot.themes.themeLight

df_stat.filter { gru_nam == "서해" }.plot{

    layout {
        title = "일별 해수 온도 변화"
        size = 2000 to 800

    }

    x("obs_datetime"){
        axis.name = "관측일시"
    }

    y {
        axis {
         //   limits = tmp_min.min().toInt().minus(1)..tmp_max.max().toInt().plus(1)
            name = "Temperature °C"
        }
    }

    line {
        y(tmp_avg)
        color("sta_nam_kor"){
            legend.name = "관측소명"
        }
        type = LineType.DOTTED
        width = 0.6
    }

    ribbon {
        yMin("tmp_min")
        yMax("tmp_max")
        fillColor("sta_nam_kor") {
            legend.name = "관측소명"
        }
        alpha = 0.6
        borderLine.width = 0.0
    }
}

In [6]:
val df_day_raw = DataFrame.readJson("http://192.168.35.107:7788/nifs/seawaterinfo/oneday")
df_day_raw.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,3005,40,0,fth59,144,null,null,bgj8a,byy87,fsch6,fwgf1,wn087
sta_nam_kor,String,3005,40,0,통영 학림,144,null,null,강릉,목포,완도 가교,태안 대야도,해남 화산
obs_datetime,String,3005,48,0,2026-01-24 13:30:00,64,null,null,2026-01-24 13:30:00,2026-01-24 19:00:00,2026-01-25 01:00:00,2026-01-25 07:30:00,2026-01-25 13:00:00
obs_lay,String,3005,3,0,1,1887,null,null,1,1,1,2,3
wtr_tmp,String,3005,133,0,8.7,183,null,null,.9,12.8,5.6,8.6,9.9
gru_nam,String,3005,3,0,남해,1524,null,null,남해,남해,남해,동해,서해
lon,Float,3005,40,0,128.415100,144,127.708832,1.189273,124.729500,126.541397,127.952202,128.699799,129.549698
lat,Float,3005,40,0,34.749802,144,35.658079,1.408086,33.310398,34.434700,34.834801,36.712299,38.368099

In [7]:
val df_day = df_day_raw.convert { wtr_tmp }.with { it.toFloat() }
df_day.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,3005,40,0,fth59,144,null,null,bgj8a,byy87,fsch6,fwgf1,wn087
sta_nam_kor,String,3005,40,0,통영 학림,144,null,null,강릉,목포,완도 가교,태안 대야도,해남 화산
obs_datetime,String,3005,48,0,2026-01-24 13:30:00,64,null,null,2026-01-24 13:30:00,2026-01-24 19:00:00,2026-01-25 01:00:00,2026-01-25 07:30:00,2026-01-25 13:00:00
obs_lay,String,3005,3,0,1,1887,null,null,1,1,1,2,3
wtr_tmp,Float,3005,133,0,8.700000,183,8.484626,3.050650,0.900000,6.700000,8.700000,10.700000,15.400000
gru_nam,String,3005,3,0,남해,1524,null,null,남해,남해,남해,동해,서해
lon,Float,3005,40,0,128.415100,144,127.708832,1.189273,124.729500,126.541397,127.952202,128.699799,129.549698
lat,Float,3005,40,0,34.749802,144,35.658079,1.408086,33.310398,34.434700,34.834801,36.712299,38.368099

In [8]:
df_day.filter { gru_nam == "동해" }.plot {

    layout {
        title = "일별 해수 온도 통계"
        size = 2000 to 800
        x.axis.name = "Observatory"
        y.axis.name = "Temperature"
    }

    boxplot(sta_nam_kor, wtr_tmp) {
        boxes {
            fillColor(Stat.middle) {
                legend{
                    name = "Temperature "
                    breaks(format = "{d}°C")
                }
                scale = continuous(Color.BLUE..Color.RED)
            }
            // Border line color depends on `x` category
            borderLine.color(Stat.x)
            // `identity` position, i.e boxes are overlapping
        }

        outliers {
            // points context + StatBoxplotOutliers context
            // color depends on `x` category
            color(Stat.x){
                legend.name = "Observatory"
            }
        }
    }
}

In [9]:
var df_current_raw = DataFrame.readJson("http://192.168.35.107:7788/nifs/seawaterinfo/current")
df_current_raw.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,64,40,0,bgna3,3,null,null,bgj8a,byy87,fsch6,fwgf1,wn087
sta_nam_kor,String,64,40,0,강릉,3,null,null,강릉,목포,완도 가교,태안 대야도,해남 화산
obs_datetime,String,64,1,0,2026-01-25 13:00:00,64,null,null,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00
obs_lay,String,64,3,0,1,40,null,null,1,1,1,2,3
wtr_tmp,String,64,40,0,8.7,4,null,null,1.2,12.9,5.7,8.7,9.8
gru_nam,String,64,3,0,남해,33,null,null,남해,남해,남해,동해,서해
lon,Float,64,40,0,128.949203,3,127.690955,1.196387,124.729500,126.577023,127.830101,128.699799,129.549698
lat,Float,64,40,0,37.799000,3,35.631267,1.420644,33.310398,34.428167,34.828501,36.672299,38.368099

In [10]:
var df_current = df_current_raw.convert { wtr_tmp  }.with { it.toFloat() }
df_current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,64,40,0,bgna3,3,null,null,bgj8a,byy87,fsch6,fwgf1,wn087
sta_nam_kor,String,64,40,0,강릉,3,null,null,강릉,목포,완도 가교,태안 대야도,해남 화산
obs_datetime,String,64,1,0,2026-01-25 13:00:00,64,null,null,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00
obs_lay,String,64,3,0,1,40,null,null,1,1,1,2,3
wtr_tmp,Float,64,40,0,8.700000,4,8.442187,3.185872,1.200000,6.900000,8.700000,10.733333,14.900000
gru_nam,String,64,3,0,남해,33,null,null,남해,남해,남해,동해,서해
lon,Float,64,40,0,128.949203,3,127.690955,1.196387,124.729500,126.577023,127.830101,128.699799,129.549698
lat,Float,64,40,0,37.799000,3,35.631267,1.420644,33.310398,34.428167,34.828501,36.672299,38.368099

In [11]:
df_current =  df_current.insert("관측층"){
    when(this.obs_lay){
        "1" -> "표층"
        "2" -> "중층"
        "3" -> "심층"
        else -> ""
    }
}.after("obs_lay")
df_current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
sta_cde,String,64,40,0,bgna3,3,null,null,bgj8a,byy87,fsch6,fwgf1,wn087
sta_nam_kor,String,64,40,0,강릉,3,null,null,강릉,목포,완도 가교,태안 대야도,해남 화산
obs_datetime,String,64,1,0,2026-01-25 13:00:00,64,null,null,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00,2026-01-25 13:00:00
obs_lay,String,64,3,0,1,40,null,null,1,1,1,2,3
관측층,String,64,3,0,표층,40,null,null,심층,중층,표층,표층,표층
wtr_tmp,Float,64,40,0,8.700000,4,8.442187,3.185872,1.200000,6.900000,8.700000,10.733333,14.900000
gru_nam,String,64,3,0,남해,33,null,null,남해,남해,남해,동해,서해
lon,Float,64,40,0,128.949203,3,127.690955,1.196387,124.729500,126.577023,127.830101,128.699799,129.549698
lat,Float,64,40,0,37.799000,3,35.631267,1.420644,33.310398,34.428167,34.828501,36.672299,38.368099

In [12]:
df_current
    .select{sta_nam_kor and wtr_tmp and "관측층"}
    .plot {
        layout {
            title = "관측 층별 해수 온도"
            size = 2600 to 800
            xAxisLabel = "Observatory"
            yAxisLabel = "Temperature( °C )"
        }

        bars {
            x(sta_nam_kor)

            y(wtr_tmp){
                scale = continuous(wtr_tmp.min().minus(1)..wtr_tmp.max().plus(1))
            }

            fillColor("관측층") {
                legend{
                    name = "Ocean Layer"
                }
                scale =  categoricalColorHue()
            }
        }
    }