In [1]:
%useLatestDescriptors
%use datetime
%use dataframe
%use kandy

In [2]:
import kotlinx.datetime.format.FormatStringsInDatetimeFormats
import kotlinx.datetime.format.byUnicodePattern

val now = Clock.System.now()

@OptIn(FormatStringsInDatetimeFormats::class)
val currentTime = now
    .toLocalDateTime(TimeZone.of("Asia/Seoul"))
    .format(LocalDateTime.Format{byUnicodePattern("yyyy-MM-dd HH:mm:ss")})

@OptIn(FormatStringsInDatetimeFormats::class)
val previous24Hour = now
    .minus(24, DateTimeUnit.HOUR)
    .toLocalDateTime(TimeZone.of("Asia/Seoul"))
    .format(LocalDateTime.Format{byUnicodePattern("yyyy-MM-dd")})

print("Current time : ${currentTime}, Previous time : ${previous24Hour}")

Current time : 2026-01-25 13:18:58, Previous time : 2026-01-24

In [3]:
val serviceKeyFilePath = "/Users/unchil/AndroidStudioProjects/full-stack-task-manager/client/src/main/resources/OceanWaterQuality.json"
val numOfRows = "1000"
val maxPage = 500

In [4]:
val serviceInfo = DataRow.readJson(path=serviceKeyFilePath)

In [5]:
import java.net.URLEncoder
import java.nio.charset.StandardCharsets
val url = "${serviceInfo.endpoint_xml}/${serviceInfo.rtmObservationInfo}?ServiceKey=${serviceInfo.key}&numOfRows=${numOfRows}&wtch_dt_start=${URLEncoder.encode(previous24Hour, StandardCharsets.UTF_8.toString())}"

In [6]:
USE{
    dependencies("org.json:json:20250107")
}

In [7]:
import org.json.XML

fun loadData(path:String, maxPage:Int): List<DataFrame<*>> {

    val rows = mutableListOf<DataFrame<*>>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toCsvStr())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item")[0] as DataFrame<*>
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (requestPage < maxPage )
    return rows
}

val dataList = loadData(url, maxPage)

Column not found: 'items'

In [8]:
val df = dataList.concat()
df.head(5)

rtmWqDoxn,rtmWqChpla,rtmWqBgalgsQy,rtmWqWtchStaCd,num,rtmWqTu,ph,rtmWqSlnty,rtmWqCndctv,rtmWqWtchDtlDt,rtmWtchWtem
13.866000,0.844000,,NEP2001,1,2,8.160000,9.549000,16.315001,2026-01-24 00:00:00.0,4.060000
10.560000,0.730000,,SEA5001,2,3,5.060000,24.627001,23.377001,2026-01-24 00:00:00.0,4.830000
11.530000,7.780000,,SEA1301,3,43,8.030000,33.522999,51.070000,2026-01-24 00:00:00.0,3.120000
9.060000,1.060000,,SEA7002,4,1,7.750000,31.347000,34.895000,2026-01-24 00:00:00.0,10.460000
10.990000,,,SEA1005,5,5,5.010000,0.672000,1.211000,2026-01-24 00:00:00.0,20.000000

item {
num string 순번
rtmWqWtchStaCd string 실시간수질관측정점코드
rtmWqWtchDtlDt string 실시간수질관측상세일시
rtmWtchWtem string 실시간관측수온
rtmWqCndctv string 실시간수질전기전도도
ph string 수소이온농도
rtmWqDoxn string 실시간수질용존산소량
rtmWqTu string 실시간수질탁도
rtmWqBgalgsQy string 실시간수질남조류량
rtmWqChpla string 실시간수질클로로필
rtmWqSlnty string 실시간수질염분
}

In [9]:
val url = "/Users/unchil/AndroidStudioProjects/full-stack-task-manager/client/src/main/resources/실시간 해양수질자동측정망 정점정보.csv"
val df_StaInfo = DataFrame.readCsv(url)
df_StaInfo.head(5)

해역구분,정점명,정점코드,경도,위도
특별관리해역,시화조력,SEA1002,126.611323,37.310004
특별관리해역,시화반월,SEA1005,126.823460,37.291451
특별관리해역,인천송도,SEA1006,126.626380,37.344882
특별관리해역,인천강화,SEA1007,126.526079,37.730790
특별관리해역,마산삼귀,SEA2004,128.595605,35.170995

In [10]:
val df_data = df.innerJoinWith(df_StaInfo){
    right.getValue<String>("정점코드") == rtmWqWtchStaCd
}
df_data.head(5)

rtmWqDoxn,rtmWqChpla,rtmWqBgalgsQy,rtmWqWtchStaCd,num,rtmWqTu,ph,rtmWqSlnty,rtmWqCndctv,rtmWqWtchDtlDt,rtmWtchWtem,해역구분,정점명,정점코드,경도,위도
13.866000,0.844000,,NEP2001,1,2,8.160000,9.549000,16.315001,2026-01-24 00:00:00.0,4.060000,하구 및 만,영산영암,NEP2001,126.448889,34.781667
10.560000,0.730000,,SEA5001,2,3,5.060000,24.627001,23.377001,2026-01-24 00:00:00.0,4.830000,특별관리해역,광양망덕,SEA5001,127.758468,34.968349
11.530000,7.780000,,SEA1301,3,43,8.030000,33.522999,51.070000,2026-01-24 00:00:00.0,3.120000,하구 및 만,천수만,SEA1301,126.456473,35.801637
9.060000,1.060000,,SEA7002,4,1,7.750000,31.347000,34.895000,2026-01-24 00:00:00.0,10.460000,특별관리해역,울산매암,SEA7002,129.387307,35.501987
10.990000,,,SEA1005,5,5,5.010000,0.672000,1.211000,2026-01-24 00:00:00.0,20.000000,특별관리해역,시화반월,SEA1005,126.823460,37.291451

In [11]:
df_data.select{ 정점명 and rtmWtchWtem }
    .groupBy{정점명}
    .sortBy { 정점명 }
    .plot{
        layout {
            title = "관측지점별 일평균 해수 온도 정보"
            size = 2000 to 1000
            //    theme = Theme.HIGH_CONTRAST_DARK
        }
        y.axis.limits = 10.0..25.0
        boxplot("정점명", "rtmWtchWtem") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("정점명"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }
    }

In [13]:
df_data.select{ 정점명 and rtmWqDoxn and rtmWqWtchDtlDt }
    .plot{
        layout {
            title = "해수 용존산소 정보"
            size = 2000 to 1000
        }
        x(rtmWqWtchDtlDt) { axis.name = "관측일시"}
        y(rtmWqDoxn) {axis.name ="용존산소"}
       // y.axis.limits = 0.0..12.0
        line{
            color(정점명){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }
        //  facetWrap(nRow = 3){ facet(gruNam)   }
    }

In [14]:
df_data.select{ 정점명 and ph and rtmWqWtchDtlDt }
    .plot{
        layout {
            title = "해수 이온농도 정보"
            size = 2000 to 1000
        }
        x(rtmWqWtchDtlDt) { axis.name = "관측일시"}
        y(ph) {axis.name ="이온농도"}
      //  y.axis.limits = 4.0..10.0
        line{
            color(정점명){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }
        //  facetWrap(nRow = 3){ facet(gruNam)   }
    }